apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: replication-controller
  name: ocm-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: replication-controller
  namespace: ocm-system
  labels:
    control-plane: replication-controller
spec:
  selector:
    matchLabels:
      control-plane: replication-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: replication-controller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        - --zap-log-level=4
        image: open-component-model/replication-controller
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: replication-controller
      terminationGracePeriodSeconds: 10
