apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: controller
  newName: controller
  newTag: latest
- name: open-component-model/replication-controller
  newName: ghcr.io/phoban01/replication-controller
  newTag: latest
