apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: open-component-model/replication-controller
  newName: ghcr.io/open-component-model/replication-controller
  newTag: v0.13.1

# Uncomment to enable HTTPS for the registry
patches:
- path: ./patches/add_root_certificates.yaml
