apiVersion: v1
kind: Service
metadata:
  name: replication-controller-metrics
  namespace: ocm-system
  labels:
    control-plane: replication-controller
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: replication-controller-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: replication-controller
    app.kubernetes.io/part-of: replication-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: metrics
  selector:
    control-plane: replication-controller
