---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replication-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentsubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentsubscriptions/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentsubscriptions/status
  verbs:
  - get
  - patch
  - update
