---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: replication-controller
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: replication-controller
  name: replication-leader-election-rolebinding
  namespace: ocm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: replication-leader-election-role
subjects:
- kind: ServiceAccount
  name: replication-controller
  namespace: ocm-system
