apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podify-subscription
  namespace: ocm-system
spec:
  serviceAccountName: service-account-for-destination
  source:
    secretRef:
      name: creds
    url: ghcr.io/open-component-model/ocm-podify
  destination:
    url: ghcr.io/open-component-model/hidden/ocm-podify
  component: "github.com/weaveworks/podify"
  interval: 10s
  semver: "=>v1-0"
  verify:
    - name: signing-key
      publicKey:
        secretRef:
          name: publickey
