apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podify-subscription
  namespace: ocm-system
spec:
  source:
    credentials:
      secretRef:
        name: creds
    url: ghcr.io/phoban01/ocm-podify
  destination:
    credentials:
      serviceAccountName: service-account-for-destination
    url: ghcr.io/skarlso/hidden/ocm-podify
  component: "github.com/weaveworks/podify"
  interval: 10s
  semver: "=>v1-0"
  verify:
    - name: phoban01
      publicKey:
        secretRef:
          name: phoban01-publickey
