apiVersion: apps/v1
kind: Deployment
metadata:
  name: replication-controller
  namespace: ocm-system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: open-component-model/replication-controller
          volumeMounts:
            - mountPath: "/etc/ssl/certs/registry-root.pem"
              subPath: "registry-root.pem"
              name: "certificates"
      volumes:
        - name: "certificates"
          secret:
            secretName: "ocm-registry-tls-certs"
            items:
              - key: "caFile"
                path: "registry-root.pem"
