name: Blackduck Scan Cronjob
on:
  schedule:
    - cron:  '0 4 * * 1'
  workflow_dispatch:
  
permissions:
  checks: write

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Blackduck Full Scan
        uses: blackduck-inc/black-duck-security-scan@805cbd09e806b01907bbea0f990723c2bb85abe9
        env:
          DETECT_PROJECT_USER_GROUPS: opencomponentmodel
          DETECT_PROJECT_VERSION_DISTRIBUTION: SAAS
          DETECT_SOURCE_PATH: ./
          NODE_TLS_REJECT_UNAUTHORIZED: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackducksca_scan_full: true
